/* Rust Web TCG — card database */

const CARDS = [
  // FRONTEND (UI)
  { no:1,  name:'Leptos',        lane:'frontend', rarity:'mythic',   cost:['UI','UI','CPU'],
    type:'Framework — Frontend · Fullstack',
    power:'4', toughness:'3',
    abilities:[
      {label:'Fine-grained', text:'Reactive signals update only what changed — no virtual DOM diff.'},
      {label:'Server Fn',    text:'⚡: Declare a Server Function callable as if it were local.'},
    ],
    flavor:'It is not the framework that renders. It is the signal that remembers.',
    flavorBy:'Leptos Book',
    stars:'17k'
  },
  { no:2,  name:'Dioxus',        lane:'frontend', rarity:'rare',     cost:['UI','UI'],
    type:'Framework — Frontend · Cross-Target',
    power:'3', toughness:'3',
    abilities:[
      {label:'Hooks',    text:'VDOM with hook-style state. Feels like React, compiles like Rust.'},
      {label:'Portable', text:'◉: Choose one — Web, Desktop, iOS, Android, TUI.'},
    ],
    flavor:'One component, any surface.',
  },
  { no:3,  name:'Yew',           lane:'frontend', rarity:'rare',     cost:['UI','UI'],
    type:'Framework — Frontend · Veteran',
    power:'3', toughness:'4',
    abilities:[
      {label:'Steady',   text:'The elder of Rust UI. Component-based, battle-worn.'},
      {label:'Mature',   text:'+1/+1 while you control a stable ecosystem.'},
    ],
    flavor:'Before there was a scene, there was Yew.',
  },
  { no:4,  name:'Sycamore',      lane:'frontend', rarity:'uncommon', cost:['UI'],
    type:'Framework — Frontend · Lightweight',
    power:'2', toughness:'2',
    abilities:[
      {label:'No VDOM', text:'Fine-grained reactivity, tiny bundles. Spiritually aligned with Solid.'},
    ],
    flavor:'Less wood. More grain.',
  },

  // BACKEND
  { no:5,  name:'Axum',          lane:'backend',  rarity:'mythic',   cost:['NET','CPU','CPU'],
    type:'Framework — Backend · Tokio',
    power:'5', toughness:'5',
    abilities:[
      {label:'Extractor', text:'Route handlers pull state, paths, headers and JSON from their own type signature.'},
      {label:'Tower',     text:'Middleware, rate-limit, trace — plug a Tower service and it just composes.'},
    ],
    flavor:'Why argue with the request? Ask types to unpack it.',
    flavorBy:'Tokio zulip'
  },
  { no:6,  name:'Actix Web',     lane:'backend',  rarity:'rare',     cost:['NET','CPU'],
    type:'Framework — Backend · Fast',
    power:'5', toughness:'3',
    abilities:[
      {label:'Throughput', text:'Historic perf leader. +2/+0 when benchmarks are involved.'},
      {label:'Actors',     text:'Optional actor runtime available when you need it.'},
    ],
    flavor:'Some services never sleep. This one never even blinks.',
  },
  { no:7,  name:'Rocket',        lane:'backend',  rarity:'rare',     cost:['NET','CPU'],
    type:'Framework — Backend · Declarative',
    power:'3', toughness:'4',
    abilities:[
      {label:'Macros',   text:'Routes, guards, forms and JSON — all declared with attributes.'},
      {label:'Batteries',text:'Templating, config, testing and fairings ship in the box.'},
    ],
    flavor:'Point the compiler. Launch.',
  },
  { no:8,  name:'Warp',          lane:'backend',  rarity:'uncommon', cost:['NET','CPU'],
    type:'Framework — Backend · Combinators',
    power:'3', toughness:'2',
    abilities:[
      {label:'Filters', text:'Routes compose from filters. Elegant for small APIs.'},
      {label:'Typed',   text:'When compilation succeeds, the shape is already right.'},
    ],
    flavor:'One filter. Then another. Then, somehow, an API.',
  },
  { no:9,  name:'Poem',          lane:'backend',  rarity:'uncommon', cost:['NET'],
    type:'Framework — Backend · OpenAPI',
    power:'2', toughness:'3',
    abilities:[
      {label:'Schema', text:'Generate an OpenAPI spec directly from your handler types.'},
    ],
    flavor:'A verse, a route, a schema.',
  },

  // FULLSTACK
  { no:10, name:'Loco',          lane:'fullstack', rarity:'rare',    cost:['CPU','NET','DB'],
    type:'Framework — Fullstack · MVC',
    power:'4', toughness:'4',
    abilities:[
      {label:'Generate',  text:'`loco generate scaffold` — models, controllers, migrations.'},
      {label:'Workers',   text:'Background jobs and mailers belong to the framework, not your glue code.'},
    ],
    flavor:'Not every track is new. Some are just well-laid.',
  },
  { no:11, name:'Perseus',       lane:'fullstack', rarity:'uncommon',cost:['UI','CPU'],
    type:'Framework — Fullstack · SSG',
    power:'3', toughness:'2',
    abilities:[
      {label:'Hybrid',  text:'Static, server-rendered, or incremental — pick per route.'},
      {label:'Built on Sycamore.'},
    ],
    flavor:'Prebuild what is knowable. Stream the rest.',
  },

  // RUNTIME
  { no:12, name:'Tokio',         lane:'runtime',  rarity:'mythic',   cost:['ASYNC','ASYNC'],
    type:'Land — Async Runtime',
    power:'∞', toughness:'∞',
    abilities:[
      {label:'Tap',        text:'◉: Add one ASYNC. This land is underneath every other card you play.'},
      {label:'Work-steal', text:'Scales cores without you thinking about cores.'},
    ],
    flavor:'If your future wakes up, it wakes up here.',
  },
  { no:13, name:'async-std',     lane:'runtime',  rarity:'uncommon', cost:['ASYNC'],
    type:'Land — Runtime',
    power:'3', toughness:'3',
    abilities:[
      {label:'Shape', text:'An async runtime modeled after `std`. Familiar, smaller world.'},
    ],
    flavor:'Like std, only it waits.',
  },
  { no:14, name:'smol',          lane:'runtime',  rarity:'uncommon', cost:['ASYNC'],
    type:'Land — Runtime',
    power:'2', toughness:'2',
    abilities:[
      {label:'Minimal', text:'A small executor and a handful of friends. Bring your own world.'},
    ],
    flavor:'Big worlds begin with small executors.',
  },

  // DATA
  { no:15, name:'SQLx',          lane:'data',     rarity:'mythic',   cost:['DB','DB'],
    type:'Artifact — Data · Async',
    power:'4', toughness:'4',
    abilities:[
      {label:'Compile-check', text:'`query!` connects to your database at build time and types the result.'},
      {label:'No ORM',        text:'Just SQL. Just rows. Just types.'},
    ],
    flavor:'If it compiles, the database already agreed.',
  },
  { no:16, name:'Diesel',        lane:'data',     rarity:'rare',     cost:['DB','CPU'],
    type:'Artifact — ORM · Schema-first',
    power:'4', toughness:'5',
    abilities:[
      {label:'Builder', text:'A strongly-typed query DSL with migrations and schema codegen.'},
    ],
    flavor:'Slower to start. Harder to break.',
  },
  { no:17, name:'SeaORM',        lane:'data',     rarity:'rare',     cost:['DB','CPU'],
    type:'Artifact — ORM · Async',
    power:'3', toughness:'3',
    abilities:[
      {label:'Entities', text:'ActiveRecord-style entities with codegen from your live schema.'},
    ],
    flavor:'For tides that change, but are still tides.',
  },

  // API / RPC
  { no:18, name:'tonic',         lane:'api',      rarity:'rare',     cost:['NET','NET'],
    type:'Framework — API · gRPC',
    power:'4', toughness:'3',
    abilities:[
      {label:'Protobuf', text:'Codegen from `.proto`; runs on Hyper + Tower.'},
      {label:'Stream',   text:'Bidi streaming, first-class.'},
    ],
    flavor:'Messages of fixed shape, conversed at wire speed.',
  },
  { no:19, name:'async-graphql', lane:'api',      rarity:'rare',     cost:['NET','CPU'],
    type:'Framework — API · GraphQL',
    power:'3', toughness:'3',
    abilities:[
      {label:'Derive',      text:'Objects, inputs, and unions from derive macros.'},
      {label:'Dataloader',  text:'Batched loading and subscriptions included.'},
    ],
    flavor:'Ask for the shape you want. Receive exactly that.',
  },
  { no:20, name:'utoipa',        lane:'api',      rarity:'uncommon', cost:['NET'],
    type:'Enchantment — OpenAPI',
    power:'2', toughness:'2',
    abilities:[
      {label:'Derive', text:'Generate an OpenAPI 3 document from your Rust types.'},
    ],
    flavor:'What the endpoints said. Written down.',
  },

  // VIEW / TEMPLATING
  { no:21, name:'Askama',        lane:'view',     rarity:'uncommon', cost:['UI'],
    type:'Enchantment — Templates',
    power:'2', toughness:'3',
    abilities:[
      {label:'Compiled', text:'Jinja-style templates, type-checked and compiled to plain Rust.'},
    ],
    flavor:'A blessing on the render path.',
  },
  { no:22, name:'Maud',          lane:'view',     rarity:'uncommon', cost:['UI'],
    type:'Enchantment — Inline HTML',
    power:'2', toughness:'2',
    abilities:[
      {label:'html!', text:'An inline HTML macro — every tag statically checked.'},
    ],
    flavor:'HTML, but the compiler read it too.',
  },
  { no:23, name:'Tera',          lane:'view',     rarity:'common',   cost:['UI'],
    type:'Enchantment — Templates · Runtime',
    power:'2', toughness:'2',
    abilities:[
      {label:'Runtime', text:'Edit templates without rebuilding. Inheritance and filters included.'},
    ],
    flavor:'When the compile loop is the wrong loop.',
  },
  { no:24, name:'reqwest',       lane:'api',      rarity:'common',   cost:['NET'],
    type:'Artifact — HTTP Client',
    power:'2', toughness:'2',
    abilities:[
      {label:'Client', text:'The calm, obvious HTTP client the rest of your service will import.'},
    ],
    flavor:'Most requests are just requests.',
  },

  // CORE — foundation crates
  { no:25, name:'serde',         lane:'core',     rarity:'mythic',   cost:['CPU','CPU'],
    type:'Enchantment — Serialization',
    power:'∞', toughness:'∞',
    abilities:[
      {label:'Derive',   text:'#[derive(Serialize, Deserialize)] — every format, one trait.'},
      {label:'Ubiquitous', text:'Half your Cargo.lock transitively depends on this card.'},
    ],
    flavor:'Every byte you ever touched passed through here.',
    flavorBy:'Every Rust project, ever'
  },
  { no:26, name:'hyper',         lane:'core',     rarity:'mythic',   cost:['NET','NET'],
    type:'Artifact — HTTP Engine',
    power:'5', toughness:'5',
    abilities:[
      {label:'Foundation', text:'The HTTP/1 + HTTP/2 implementation Axum, reqwest and tonic all stand on.'},
      {label:'Low-level',  text:'You can reach past your framework and touch the wire directly.'},
    ],
    flavor:'Somewhere under every Rust service, a hyper task is listening.',
  },
  { no:27, name:'tower',         lane:'core',     rarity:'rare',     cost:['CPU','NET'],
    type:'Enchantment — Middleware',
    power:'3', toughness:'4',
    abilities:[
      {label:'Service',  text:'One trait — `Service<Request>` — composes rate-limits, retries, auth, tracing.'},
      {label:'Reusable', text:'The same layers work in Axum, tonic, and any custom hyper stack.'},
    ],
    flavor:'Every request climbs the tower, and every response comes back down.',
  },
  { no:28, name:'tracing',       lane:'core',     rarity:'rare',     cost:['CPU'],
    type:'Enchantment — Observability',
    power:'3', toughness:'3',
    abilities:[
      {label:'Spans',   text:'Structured, async-aware spans that survive `.await` points.'},
      {label:'Subscribers', text:'Plug a subscriber — pretty logs, OpenTelemetry, Jaeger — same events.'},
    ],
    flavor:'println! for the first service. tracing for the tenth.',
  },
  { no:29, name:'anyhow',        lane:'core',     rarity:'uncommon', cost:['CPU'],
    type:'Artifact — Error · Application',
    power:'2', toughness:'3',
    abilities:[
      {label:'Context', text:'.context("while reading config") — errors that know where they were.'},
      {label:'One Type', text:'`anyhow::Result` — one error, any source. Perfect for binaries.'},
    ],
    flavor:'For when you just need the error to tell you what happened.',
  },
  { no:30, name:'thiserror',     lane:'core',     rarity:'uncommon', cost:['CPU'],
    type:'Artifact — Error · Library',
    power:'2', toughness:'3',
    abilities:[
      {label:'Derive',   text:'#[derive(Error)] — zero-cost typed errors with Display and source().'},
      {label:'Library',  text:'The dual of anyhow. Use in crates you publish.'},
    ],
    flavor:'Anyhow for apps. This one, for the library you ship.',
  },

  // TOOLS — build & dev
  { no:31, name:'cargo',         lane:'tools',    rarity:'mythic',   cost:['CPU'],
    type:'Land — Package Manager',
    power:'∞', toughness:'∞',
    abilities:[
      {label:'Tap',      text:'◉: `cargo build`. ◉: `cargo test`. ◉: `cargo run`.'},
      {label:'Workspaces', text:'One lockfile. Many crates. Shared target/.'},
    ],
    flavor:'Rust without cargo is just a compiler looking for a home.',
  },
  { no:32, name:'wasm-bindgen',  lane:'tools',    rarity:'rare',     cost:['UI','CPU'],
    type:'Enchantment — Rust ↔ JS Bridge',
    power:'3', toughness:'3',
    abilities:[
      {label:'ABI',      text:'Call JS from Rust. Call Rust from JS. Types cross the boundary intact.'},
      {label:'Foundation', text:'Everything WASM on the web stands on this card.'},
    ],
    flavor:'The border crossing where Rust and JavaScript shake hands.',
  },
  { no:33, name:'trunk',         lane:'tools',    rarity:'uncommon', cost:['UI'],
    type:'Artifact — WASM Bundler',
    power:'3', toughness:'2',
    abilities:[
      {label:'Index.html', text:'Point it at an HTML file; it compiles, bundles and serves the rest.'},
      {label:'Live',       text:'Hot-reload dev server for Leptos, Yew, Dioxus, Sycamore.'},
    ],
    flavor:'You write the index; trunk writes the pipeline.',
  },
  { no:34, name:'clap',          lane:'tools',    rarity:'rare',     cost:['CPU'],
    type:'Artifact — CLI Builder',
    power:'3', toughness:'4',
    abilities:[
      {label:'Derive',  text:'#[derive(Parser)] — structs become argument parsers, flags and subcommands.'},
      {label:'Help',    text:'--help, shell completion, colored errors — all included.'},
    ],
    flavor:'Every Rust CLI you have ever loved starts the same way: use clap::Parser.',
  },
];

window.CARDS = CARDS;
